name: firestore
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: any
  logger: any

# dev_dependencies:
#  test: ^1.6.0
