name: firestore
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: any
  logger: any
  firebase_admin_interop: any

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
#  test: ^1.6.0
